mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wasteweb/', include('wasteweb.urls')),
    url(r'^report_builder/', include('report_builder.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

mysite/wasteweb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    path('error/', views.error, name='error'),
    path('tentang/', views.tentang, name='tentang'),
    path('kontak/', views.kontak, name='kontak'),
    path('report/', views.report, name='report'),
    path('opdata/', views.opdata, name='opdata'),
    path('bsdata/', views.bsdata, name='bsdata'),
    path('updateBSdata/<int:id>/', views.updateBSdata, name='updateBSdata'),
    path('updateOPdata/<int:id>/', views.updateOPdata, name='updateOPdata'),
    path('TambahBSForm_view/', views.TambahBSForm_view, name='TambahBSForm_view'),
    path('TambahOPForm_view/', views.TambahOPForm_view, name='TambahOPForm_view'),
    path('hapusBSdata/<int:id>/', views.hapusBSdata, name='hapusBSdata'),
    path('hapusOPdata/<int:id>/', views.hapusOPdata, name='hapusOPdata'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
app_name = 'wasteweb'

mysite/wasteweb/models.py
from django.db import models

class Sampah(models.Model):
    nama_sampah = models.CharField(max_length=100)
    kategori_sampah = models.CharField(max_length=100)
    keterangan = models.TextField()
    def __str__(self):
        return self.nama_sampah

class LokasiKecamatan(models.Model):
    nama_lokasi_kec = models.CharField(max_length=100)
    keterangan = models.TextField()
    def __str__(self):
        return self.nama_lokasi_kec

class AngkutanTrukSampah(models.Model):
    nama_angkutan_truk = models.CharField(max_length=100)
    deskripsi_angkutan = models.TextField()
    def __str__(self):
        return self.nama_angkutan_truk

class InputBS(models.Model):
    nama_sampah = models.ForeignKey(Sampah, on_delete=models.CASCADE)
    nama_lokasi = models.ForeignKey(LokasiKecamatan, on_delete=models.CASCADE)
    tanggal = models.DateField(max_length=100)
    jumlah = models.IntegerField()

class InputOP(models.Model):
    nama_sampah = models.ForeignKey(Sampah, on_delete=models.CASCADE)
    nama_lokasi = models.ForeignKey(LokasiKecamatan, on_delete=models.CASCADE)
    nama_angkutan_truk = models.ForeignKey(AngkutanTrukSampah, on_delete=models.CASCADE)
    tanggal = models.DateField(max_length=100)
    jam = models.TimeField(max_length=100)
    jumlah = models.IntegerField()

mysite/wasteweb/forms.py
from django.conf import settings
from django import forms
from django.forms import ModelForm
from .models import Sampah, LokasiKecamatan, AngkutanTrukSampah, InputBS, InputOP


class TambahBSForm(ModelForm):
    """
    Render the basic crud create form
    """
    nama_sampah = forms.ModelChoiceField(queryset=Sampah.objects.all())

    nama_lokasi = forms.ModelChoiceField(queryset=LokasiKecamatan.objects.all())

    tanggal = forms.DateField(
        widget=forms.SelectDateWidget(attrs={
            'class': 'form-control', 'placeholder': 'Tanggal'}))

    jumlah = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control',
                                     'placeholder': 'Masukkan jumlah sampah'}))

    class Meta:
        model = InputBS
        fields = ('nama_sampah', 'nama_lokasi', 'tanggal', 'jumlah')

class TambahOPForm(ModelForm):
    """
    Render the basic crud create form
    """
    nama_sampah = forms.ModelChoiceField(queryset=Sampah.objects.all())

    nama_lokasi = forms.ModelChoiceField(queryset=LokasiKecamatan.objects.all())

    nama_angkutan_truk = forms.ModelChoiceField(queryset=AngkutanTrukSampah.objects.all())

    tanggal = forms.DateField(
        widget=forms.SelectDateWidget(attrs={
            'class': 'form-control', 'placeholder': 'Tanggal'}))

    jam = forms.TimeField(
        widget=forms.TimeInput(attrs={
            'class': 'form-control', 'placeholder': 'Jam'}))

    jumlah = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': 'form-control',
                                     'placeholder': 'Masukkan jumlah sampah'}))

    class Meta:
        model = InputOP
        fields = ('nama_sampah', 'nama_lokasi', 'nama_angkutan_truk', 'tanggal', 'jam', 'jumlah')

mysite/wasteweb/views.py
from django.http import Http404
from django.shortcuts import render,
from django.http import HttpResponse
from .decorators import operator_login_required
from .decorators import banksampah_login_required
from .models import InputBS, InputOP

from django.conf import settings
from django.http import JsonResponse
from django.utils.text import slugify
from django.db.models import Q

import json
import pytz
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import redirect
# Call myroot properties
from .forms import TambahBSForm, TambahOPForm
from datetime import datetime, timedelta
from itertools import chain

def dict_alert_msg(form_is_valid, alert_title, alert_msg, alert_type):
    """
    Function to call internal alert message to the user with the required
    paramaters: form_is_valid[True/False all small letters for json format],
    alert_title='string', alert_msg='string',
    alert_type='success, error, warning, info'
    """
    data = {
        'form_is_valid': form_is_valid,
        'alert_title': alert_title,
        'alert_msg': alert_msg,
        'alert_type': alert_type
    }
    return data


def convert_to_local_datetime(dt_value):
    MY_DT_FORMAT = '%Y-%m-%d %H:%M:%S'
    dt = dt_value
    created_date_str = dt.strftime(MY_DT_FORMAT)  # convert to string
    created_date = dt.strptime(created_date_str, MY_DT_FORMAT)

    # timeago in python library to get user's local time
    now = datetime.now() + timedelta(seconds=60 * 3.4)
    event_date = timeago.format(created_date, now)

    return str(event_date)



def index(request):
    return render(request, 'wasteweb/index.html')

def tentang(request):
    return render(request, 'wasteweb/tentang.html')

def kontak(request):
    return render(request, 'wasteweb/kontak.html')

def login(request):
    return render(request, 'accounts/login/')

def logout(request):
    return render(request, 'accounts/logout/')

def error(request):
    return render(request, 'wasteweb/404.html')

def report(request):
    if request.method == "GET":

        q1 = InputOP.objects.all().order_by('-id')[:50]
        q2 = InputBS.objects.all().order_by('-id')[:50]  # fetch the latest 50 rows
        db_data = chain(q1,q2)

        return render(request, 'wasteweb/report.html',
                      {
                          'title': 'Input Data Sampah Kota Semarang',
                          'meta_desc': 'Sistem Informasi Pengelolaan Data Sampah Kota Semarang',
                          'db_data': db_data,
                      })
    else:
        return HttpResponse('/wasteweb/error/', context_instance=RequestContext(request))

@banksampah_login_required
def TambahBSForm_view(request):
        form = TambahBSForm(request.POST or None)
        if form.is_valid():
            form.save()  # insert new row
            return redirect('/wasteweb/bsdata')
        return render(request, 'wasteweb/tambah_bs.html', {'form': form})

@operator_login_required
def TambahOPForm_view(request):
    form = TambahOPForm(request.POST or None)
    if form.is_valid():
        form.save()  # insert new row
        return redirect('/wasteweb/opdata')
    return render(request, 'wasteweb/tambah_op.html', {'form': form})

@banksampah_login_required
def bsdata(request):
    if request.method == "GET":

        db_data = InputBS.objects.all().order_by('-id')[:50]  # fetch the latest 50 rows

        return render(request, 'wasteweb/bsdata.html',
                      {
                          'title': 'Input Data Sampah Kota Semarang',
                          'meta_desc': 'Sistem Informasi Pengelolaan Data Sampah Kota Semarang',
                          'db_data': db_data
                       })
    else:
        return HttpResponse('/wasteweb/error/', context_instance=RequestContext(request))

@operator_login_required
def opdata(request):
    if request.method == "GET":

        db_data = InputOP.objects.all().order_by('-id')[:50]  # fetch the latest 50 rows

        return render(request, 'wasteweb/opdata.html',
                      {
                          'title': 'Input Data Sampah Kota Semarang',
                          'meta_desc': 'Sistem Informasi Pengelolaan Data Sampah Kota Semarang',
                          'db_data': db_data
                       })
    else:
        return HttpResponse('/wasteweb/error/', context_instance=RequestContext(request))

@banksampah_login_required
def hapusBSdata(request, id):
    hapusbs = InputBS.objects.get(id=id)
    hapusbs.delete()
    return redirect('/wasteweb/bsdata')
    return render(request, 'wasteweb/hapusBSdata.html', {'hapusbs': hapusbs})

@operator_login_required
def hapusOPdata(request, id):
    hapusop = InputOP.objects.get(id=id)
    hapusop.delete()
    return redirect('/wasteweb/opdata')
    return render(request, 'wasteweb/hapusOPdata.html', {'hapusop': hapusop})

@banksampah_login_required
def updateBSdata(request, id):
    if request.method == "GET":

        # Get the selected row information
        db_data = InputBS.objects.filter(id=id)

        if db_data:

            # Edit form data
            edit_data = InputBS.objects.get(id=id)
            formEdit = TambahBSForm(instance=edit_data)

            return render(request, 'wasteweb/updateBSdata.html',
                          {
                              'title': 'Update Input Data Sampah Kota Semarang',
                              'meta_desc': 'Sistem Informasi Pengelolaan Data Sampah Kota Semarang',
                              'id': id,
                              'formEdit': formEdit
                          })
        else:
            raise Http404()

    data = dict()
    if request.method == "POST":

        # Get the  form modified data
        form_edit = TambahBSForm(request.POST)
        id = request.POST.get('id')

        if form_edit.is_valid():

            # Check if the row still not deleted
            if InputBS.objects.filter(id=id).exists():

                # Get the form edit instance
                update_data = InputBS.objects.get(id=id)

                # Now, supply the form data to an instance
                form_edit = TambahBSForm(request.POST, instance=update_data)
                form_edit.save()  # Finally save the form data

            return redirect('/wasteweb/bsdata')
            return render(request, 'wasteweb/updateBSdata.html', {'form_edit': form_edit})


@operator_login_required
def updateOPdata(request, id):
    if request.method == "GET":

        # Get the selected row information
        db_data = InputOP.objects.filter(id=id)

        if db_data:

            # Edit form data
            edit_data = InputOP.objects.get(id=id)
            formEdit = TambahOPForm(instance=edit_data)

            return render(request, 'wasteweb/updateopdata.html',
                          {
                              'title': 'Update Input Data Sampah Kota Semarang',
                              'meta_desc': 'Sistem Informasi Pengelolaan Data Sampah Kota Semarang',
                              'id': id,
                              'formEdit': formEdit
                          })
        else:
            raise Http404()

    data = dict()
    if request.method == "POST":

        # Get the  form modified data
        form_edit = TambahOPForm(request.POST)
        id = request.POST.get('id')

        if form_edit.is_valid():

            # Check if the row still not deleted
            if InputOP.objects.filter(id=id).exists():

                # Get the form edit instance
                update_data = InputOP.objects.get(id=id)

                # Now, supply the form data to an instance
                form_edit = TambahOPForm(request.POST, instance=update_data)
                form_edit.save()  # Finally save the form data

            return redirect('/wasteweb/opdata')
            return render(request, 'wasteweb/updateOPdata.html', {'form_edit': form_edit})


@banksampah_login_required
def bsdata_search_text_view(request):
    if request.method == "POST":
        fsearch = request.POST.get('fsearch')

        # Filter data by using __icontains built-in Django function
        data_lists = InputBS.objects.filter(
                        (Q(nama_sampah__icontains=fsearch) |
                        Q(nama_lokasi__icontains=fsearch) |
                        Q(tanggal__icontains=fsearch) |
                        Q(jumlah__icontains=fsearch))).order_by('-id')[:50]

        fh_data = dict()
        fh_list = []

        for fh in data_lists:
            url = settings.BASE_URL + slugify(fh.nama_sampah) + "-" + str(fh.id)
            trun_nama_lokasi = fh.nama_lokasi[:100] + '...'

            # Convert UTC datetime from db to user's local datetime.
            submitted_date = convert_to_local_datetime(fh.submitted)

            edit_url = settings.BASE_URL + "updateBSdata/" + str(fh.id) + "/change/"

            fh_list.append(
                    {'nama_sampah': (fh.nama_sampah),
                     'nama_lokasi': trun_nama_lokasi,
                     'tanggal': fh.tanggal,
                     'jumlah': fh.jumlah,
                     'submitted': submitted_date,
                     'id': fh.id,
                     'url': url,
                     'edit_url': edit_url
                     })

        fh_data = fh_list
        json_data = json.dumps(fh_data)
        return JsonResponse(json_data, safe=False)

@operator_login_required
def opdata_search_text_view(request):
    if request.method == "POST":
        fsearch = request.POST.get('fsearch')

        # Filter data by using __icontains built-in Django function
        data_lists = InputOP.objects.filter(
                        (Q(nama_sampah__icontains=fsearch) |
                        Q(nama_lokasi__icontains=fsearch) |
                        Q(nama_angkutan_truk__icontains=fsearch) |
                        Q(tanggal__icontains=fsearch) |
                        Q(jam__icontains=fsearch) |

mysite/wasteweb/templates/wasteweb/tambah_op.html
{% load static %}
{% load auth_extras %}
{% load render_table from django_tables2 %}
{% load humanize %}
{% load tz %}
{% load i18n %}
<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>Sistem Pengelolaan Data Sampah Kota Semarang</title>
	<!-- Meta tag Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8" />
	<meta name="keywords" content="Sistem Pengelolaan Data Sampah Kota Semarang" />
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!-- //Meta tag Keywords -->

	<!-- Custom-Files -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Bootstrap-Core-CSS -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
	<!-- Style-CSS -->
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<!-- Font-Awesome-Icons-CSS -->
	<!-- //Custom-Files -->

	<!-- Web-Fonts -->
	<link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=devanagari,latin-ext"
	 rel="stylesheet">
	<!-- //Web-Fonts -->

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

	<link rel="stylesheet" href="{% static 'daterangepicker/daterangepicker-bs3.css' %}">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.bootstrap4.min.css">

</head>

<body>
	<!-- main banner -->
	<div class="main-top" id="home">
		<!-- header -->
		<header>
			<div class="container-fluid">
				<div class="header d-lg-flex justify-content-between align-items-center py-3 px-sm-3">
					<!-- logo -->
					<div id="logo">
						<h1><a href="{% url 'wasteweb:index' %}"><span class="fa fa-linode mr-2"></span>Sistem PDSK Semarang</a></h1>
					</div>
					<!-- //logo -->
					<!-- nav -->
					<div class="nav_w3ls">
						<nav>
							<label for="drop" class="toggle">Menu</label>
							<input type="checkbox" id="drop" />
							<ul class="menu">
								<li><a href="{% url 'wasteweb:index' %}" class="active">Beranda</a></li>
								<li><a href="{% url 'wasteweb:tentang' %}">Tentang</a></li>
								<li><a href="{% url 'wasteweb:report' %}">Report</a></li>
								<li><a href="{% url 'wasteweb:kontak' %}">Kontak</a></li>
                                {% if request.user|has_group:"banksampah" %}
                                <li><a href="{% url 'wasteweb:bsdata' %}">Input Data (Bank Sampah)</a></li>
								<li><a href="{% url 'logout' %}">Logout</a></li>
								{% elif request.user|has_group:"operator" %}
								<li><a href="{% url 'wasteweb:opdata' %}">Input Data (Operator)</a></li>
								<li><a href="{% url 'logout' %}">Logout</a></li>
                                {% else %}
                                <li><a href="{% url 'login' %}">Login</a></li>
                                {% endif %}
							</ul>
						</nav>
					</div>
					<!-- //nav -->
					<div class="d-flex mt-lg-1 mt-sm-2 mt-3 justify-content-center">
						<!-- download -->
						<a class="dwn-w3ls btn" href="http://w3layouts.com/" target="_blank">
							<span class="fa fa-cloud-download"></span>
						</a>
						<!-- //download -->
					</div>
				</div>
			</div>
		</header>
		<!-- //header -->

        <br>
        <center><h3>Menambahkan Input Data Sampah (Operator)</h3></center>
        <br>
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 order-md-1">

                <form id="TambahOPForm" class="" method="POST">
                    {% csrf_token %}

                    <div class="form-label-group">
                        <label for="id_nama_sampah">Nama Sampah</label>
                        {{ form.nama_sampah }}
                    </div>

                    <div class="form-label-group">
                        <label for="id_nama_lokasi">Nama Lokasi</label>
                        {{ form.nama_lokasi }}
                    </div>

					<div class="form-label-group">
                        <label for="id_nama_angkutan_truk">Nama Angkutan Truk</label>
                        {{ form.nama_angkutan_truk }}
					</div>

                    <div class="form-label-group">
                        <label for="id_tanggal">Tanggal</label>
                        {{ form.tanggal }}
                    </div>

                    <div class="form-label-group">
                        <label for="id_jam">Jam</label>
                        {{ form.jam }}
                    </div>

                    <div class="form-label-group">
                        <label for="id_jumlah">Jumlah</label>
                        {{ form.jumlah }}
                    </div>

					<br>
                <div class="">
                    <button class="btn btn-lg btn-primary btn-block" onclick="saveForm();" id="btnInputOP">Tambahkan Data</button>
                </div>
                </form>


            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/common.js' %}" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.min.js" defer></script>
<script src="{% static 'sweetalert/sweetalert.js' %}" defer></script>

<script>
    var BASE_URL = "{{ BASE_URL }}";
    function saveForm()
    {
        //Get the form instance
        var $form = $("#TambahOPForm");
        id_nama_sampah = $("#id_nama_sampah").val();
        id_nama_lokasi = $("#id_nama_lokasi").val();
        id_nama_angkutan_truk = $("#id_nama_angkutan_truk").val();
        id_tanggal = $("#id_tanggal").val();
        id_jam = $("#id_jam").val();
        id_jumlah = $("#id_jumlah").val();
        if (id_nama_sampah === undefined || id_nama_sampah === null || id_nama_sampah ===""){
            swal("Nama Sampah is Required!", "Please enter your nama sampah", "error");
            $("#id_nama_sampah").focus();
            return false;
    }
        if (id_nama_lokasi === undefined || id_nama_lokasi === null || id_nama_lokasi ===""){
            swal("nama_lokasi is Required!", "Please enter your nama_lokasi", "error");
            $("#id_nama_lokasi").focus();
            return false;
        }
        if (id_nama_angkutan_truk === undefined || id_nama_angkutan_truk === null || id_nama_angkutan_truk ===""){
            swal("nama_angkutan_truk is Required!", "Please enter your nama_angkutan_truk", "error");
            $("#id_nama_angkutan_truk").focus();
            return false;
        }
        if (id_tanggal === undefined || id_tanggal === null || id_tanggal ===""){
            swal("Tanggal is Required!", "Please enter your message", "error");
            $("#id_tanggal").focus();
            return false;
        }
        if (id_jam === undefined || id_jam === null || id_jam ===""){
            swal("Jam is Required!", "Please enter your message", "error");
            $("#id_jam").focus();
            return false;
        }
        if (id_jumlah === undefined || id_jumlah === null || id_jumlah ===""){
            swal("Jumlah is Required!", "Please enter your message", "error");
            $("#id_jumlah").focus();
            return false;
        }
        $.ajax({
            method: "POST",
            url: BASE_URL+'TambahOPForm_view/',
            data: $form.serialize(),
            cache: false,
            dataType: "json",
            beforeSend: function(){
                //Start displaying button's working animation
                var loadingText = '<i class="fa fa-circle-o-notch fa-spin"></i> working...';
                if ($("#btnTambahOPForm").html() !== loadingText) {
                    $("#btnTambahOPForm").data('original-text', $("#btnTambahOPForm").html());
                    $("#btnTambahOPForm").html(loadingText);
                }
            },
            success: function(jResults)
            {
                $("#btnTambahOPForm").html($("#btnTambahOPForm").data('original-text')); //stop animation and switch back to original text
                if(jResults.alert_type =='success'){
                    swal(jResults.alert_title, jResults.alert_msg, jResults.alert_type);
                    $form[0].reset(); // reset form data
                    $("#id_message").summernote("reset");
                    $("#id_nama_sampah").focus();
                }
                else {
                    var strErr = jResults.alert_msg + '';
                    strErr = strErr.split(",").pop();
                    swal(jResults.alert_title, strErr, jResults.alert_type);
                }
            }
        });
    }
    $(document).ready(function()
    {
        $('#id_message').summernote({
            placeholder: 'Type your message here.',
            tabsize: 2,
            height: 300
        });
    });
</script>
{% endblock %}

</div>
	<!-- copyright bottom -->
	<div class="copy-bottom bg-li py-4 border-top">
		<div class="container-fluid">
			<div class="d-md-flex px-md-3 position-relative text-center">
				<!-- footer social icons -->
				<div class="social-icons-footer mb-md-0 mb-3">
					<ul class="list-unstyled">
						<li>
							<a href="http://facebook.com/DLHSemarang">
								<span class="fa fa-facebook"></span>
							</a>
						</li>
						<li>
							<a href="http://twitter.com/dlhkotasemarang">
								<span class="fa fa-twitter"></span>
							</a>
						</li>
						<li>
							<a href="dlh.semarangkota@gmail.com">
								<span class="fa fa-google-plus"></span>
							</a>
						</li>
						<li>
							<a href="http://instagram.com/dlh.semarang">
								<span class="fa fa-instagram"></span>
							</a>
						</li>
					</ul>
				</div>
				<!-- //footer social icons -->
				<!-- copyright -->
				<div class="copy_right mx-md-auto mb-md-0 mb-3">
					<p class="text-bl let">© 2019 Sistem Pengelolaan Data Sampah Kota Semarang. All rights reserved | Desain oleh
						<a href="http://dlh.semarangkota.go.id/" target="_blank">DLHK Kota Semarang</a>
					</p>
				</div>
				<!-- //copyright -->
				<!-- move top icon -->
				<a href="#home" class="move-top text-center">
					<span class="fa fa-level-up" aria-hidden="true"></span>
				</a>
				<!-- //move top icon -->
			</div>
		</div>
	</div>
	<!-- //copyright bottom -->

</body>

</html>